### PR TITLE
1533 creation of reference paths in passive transports broken

### LINKED ISSUE #1533: Creation of reference paths in passive transports broken
When creating alias references for equations in the Pasive Transport formulas by "drag-and-drop", some generated paths are incorrect, the behavior changed as compared to v11, or I think the behavior was not completely right in the first place. I collected the different use cases in the tables below and compared the generated paths between v11 and v12

image

1. Export any PK-Sim simulation to MoBi
2. Open the "Passive Transports" BB
3. Select transport `PassiveDiffusionInt2Cell`. The transport has `Interstitial` as `SOURCE` and `Intracellular` as `TARGET`
4. Switch to the tab "Kinetic". Drag-and-drop the different parameters.

I marked cases that behave differently from expected in ${\color{red}red}$.

## Absolute path

When "Absolute paths" should be created:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#467886" vlink="#96607D">

  | Parameter | V11 | V12 | Expected
-- | -- | -- | -- | --
1 | Organism\|Age | Organism\|Age | Organism\|Age | Organism\|Age
2 | Organism\|Bone\|Volume | Organism\|Bone\|Volume | Organism\|Bone\|Volume | Organism\|Bone\|Volume
3 | Organism\|Bone\|Interstitial\|Volume | Organism\|Bone\|Interstitial\|Volume | Organism\|Bone\|Interstitial\|Volume | Organism\|Bone\|Interstitial\|Volume
4 | Organism\|Bone\|Interstitial\|Aciclovir | $${\color{red}SOURCE\|Aciclovir}$$  | $${\color{red}SOURCE\|Aciclovir}$$ | Organism\|Bone\|Interstitial\|Aciclovir
5 | Organism\|Bone\|Interstitial\|Aciclovir\|Concentration | $${\color{red}SOURCE\|Aciclovir\|Concentration}$$ | $${\color{red}NOT POSSIBLE}$$ | Organism\|Bone\|Interstitial\|Aciclovir\|Concentration
6 | Organism\|Bone\|Plasma\|Aciclovir | Organism\|Bone\|Plasma\|Aciclovir | Organism\|Bone\|Plasma\|Aciclovir | Organism\|Bone\|Plasma\|Aciclovir
7 | Organism\|Bone\|Plasma\|Aciclovir\|Concentration | Organism\|Bone\|Plasma\|Aciclovir\|Concentration | $${\color{red}NOT POSSIBLE}$$ | Organism\|Bone\|Plasma\|Aciclovir\|Concentration
8 | Neighborhoods\|ArterialBlood_bc_Bone_bc\|Aciclovir | Neighborhoods\|ArterialBlood_bc_Bone_bc\|Aciclovir | Neighborhoods\|ArterialBlood_bc_Bone_bc\|Aciclovir | Neighborhoods\|ArterialBlood_bc_Bone_bc\|Aciclovir
9 | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir
10 | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir\|P   (interstitial->intracellular) | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir\|P   (interstitial->intracellular) | $${\color{red}NOT POSSIBLE}$$ | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir\|P   (interstitial->intracellular)
11 | Aciclovir\|Aqueous diffusion coefficient | Aciclovir\|Aqueous diffusion coefficient | Aciclovir\|Aqueous diffusion coefficient | Aciclovir\|Aqueous diffusion coefficient

</body>

</html>

- Case 4 - the created path contains the keyword `MOLECULE`. I think that in case of absolute paths, the specific molecule name should be inserted.
- Case 5 - same as Case 4 for v11. In v12, molecule parameters can not be used at all.
- Cases 7 and 10 - molecule property cannot be added in v12 (this was possible at some point).

## Relative path
Local reference point: `Organism|Bone|Intracellular`

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

12 | Organism\|Age | ..\|..\|..\|..\|Age | ..\|..\|..\|..\|Age | ..\|..\|..\|..\|Age
-- | -- | -- | -- | --
13 | Organism\|Bone\|Volume | ..\|..\|..\|Volume | ..\|..\|..\|Volume | ..\|..\|..\|Volume
14 | Organism\|Brain\|Volume | ..\|..\|..\|..\|Brain\|Volume | ..\|..\|..\|..\|Brain\|Volume | ..\|..\|..\|..\|Brain\|Volume
15 | Organism\|Bone\|Interstitial\|Volume | SOURCE\|Volume | SOURCE\|Volume | SOURCE\|Volume
16 | Organism\|Brain\|Interstitial\|Volume | SOURCE\|Volume | SOURCE\|Volume | SOURCE\|Volume
17 | Organism\|Bone\|Interstitial\|Aciclovir | SOURCE\|MOLECULE | SOURCE\|MOLECULE | SOURCE\|MOLECULE
18 | Organism\|Bone\|Interstitial\|Aciclovir\|Concentration | SOURCE\|MOLECULE\|Concentration | ${\color{red}..\|..\|Aciclovir\|Concentration}$ | SOURCE\|MOLECULE\|Concentration
19 | Organism\|Bone\|Plasma\|Aciclovir | ${\color{red}..\|..\|..\|Plasma\|Aciclovir}$ | ${\color{red}..\|..\|..\|Plasma\|Aciclovir}$ | ..\|..\|..\|Plasma\|MOLECULE
20 | Organism\|Bone\|Plasma\|Aciclovir\|Concentration | ${\color{red}..\|..\|..\|Plasma\|Aciclovir\|Concentration}$ | ${\color{red}..\|..\|Aciclovir\|Concentration}$ | ..\|..\|..\|Plasma\|MOLECULE\|Concentration
21 | Neighborhoods\|ArterialBlood_bc_Bone_bc\|Aciclovir | ${\color{red}..\|..\|..\|..\|..\|Neighborhoods\|ArterialBlood_bc_Bone_bc\|Aciclovir}$ | ${\color{red}..\|..\|..\|..\|..\|Neighborhoods\|ArterialBlood_bc_Bone_bc\|Aciclovir}$ | ..\|..\|..\|..\|..\|Neighborhoods\|ArterialBlood_bc_Bone_bc\|MOLECULE
22 | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir | ${\color{red}..\|..\|..\|..\|..\|Neighborhoods\|Bone_int_Bone_cell\|Aciclovir}$ | ${\color{red}..\|..\|..\|..\|..\|Neighborhoods\|Bone_int_Bone_cell\|Aciclovir}$ | NEIGHBORHOOD\|MOLECULE
23 | Neighborhoods\|Bone_int_Bone_cell\|Aciclovir\|P   (interstitial->intracellular) | ${\color{red}..\|..\|..\|..\|..\|Neighborhoods\|Bone_int_Bone_cell\|Aciclovir\|P   (interstitial->intracellular)}$ | ${\color{red}..\|..\|..\|..\|..\|Neighborhoods\|Bone_int_Bone_cell\|MOLECULE\|P   (interstitial->intracellular)}$ | NEIGHBORHOOD\|MOLECULE\|P (interstitial->intracellular)
24 | Aciclovir\|Aqueous diffusion coefficient | ${\color{red}Aciclovir\|Aqueous diffusion coefficient}$ | ${\color{red}Aciclovir\|Aqueous diffusion coefficient}$ | MOLECULE\|Aqueous diffusion coefficient

- Case 18 - molecule name is not substituted by `MOLECULE` and the path is not substituted by `SOURCE` in v12

- Case 19, 24 - Aciclovir should be substituted by `MOLECULE`
- Case 20 - v12 generates the path with one `..|` less than v11 and no `Plasma`. Furthermore, I think the `MOLECULE` keyword should be used
- Case 21: Use `MOLECULE`?
- Case 22: Can the keyword `NEIGHBORHOOD` be used`
- Case 23: as Case 22, plus v12 substitutes `Aciclovir` by `MOLECULE` (which I would expect) and v11 does not

</body>

</html>

@Yuri05  @msevestre what do you think?

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #1533 

# Description

Creation of reference paths in passive transports broken.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image

image

# Questions (if appropriate):

@PavelBal 
For this 2 cases:
image

The expected is different:
image

Would you please let me know why? And how to differenciate one from the other?

Thanks.

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs [hunk 1]
```diff
@@ -35,15 +35,21 @@ public ObjectPathCreatorAtTransport(IObjectPathFactory objectPathFactory, IAlias
...
+         if (firstPathElement.IsNullOrEmpty() || shouldCreateAbsolutePaths)
+         {
+            var dto = base.CreatePathFromParameterDummy(objectBaseDTO, shouldCreateAbsolutePaths, refObject, editedObject);
+            if (!shouldCreateAbsolutePaths)
+               dto.Path.Replace(dtoDummyParameter.ModelParentName, ObjectPathKeywords.MOLECULE);
+
+            return dto;
+         }
 
          var moleculeElement = shouldCreateAbsolutePaths ? dtoDummyParameter.ModelParentName : ObjectPathKeywords.MOLECULE;
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs:49]: I'm a bit confused about this because the line here has not been changed by this PR. However, the `shouldCreateAbsolutePaths` will always be false by this point. Is it the case that the conditional here is not required at all now?

If so, you can remove it.

Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs:49]: I'm a bit confused about this because the line here has not been changed by this PR. However, the `shouldCreateAbsolutePaths` will always be false by this point. Is it the case that the conditional here is not required at all now?

If so, you can remove it.

File: src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs [hunk 2]
```diff
@@ -52,14 +58,19 @@ public override ReferenceDTO CreateMoleculePath(DummyMoleculeContainerDTO dtoObj
...
-            return base.CreateMoleculePath(dtoObjectBase, shouldCreateAbsolutePaths, refObject);
+         if (firstPathElemnt.IsNullOrEmpty() || shouldCreateAbsolutePaths)
+         {
+            var dto = base.CreateMoleculePath(dtoObjectBase, shouldCreateAbsolutePaths, refObject);
+            if (!shouldCreateAbsolutePaths)
+               dto?.Path.Replace(dtoObjectBase.Name, ObjectPathKeywords.MOLECULE);
+            return dto;
+         }
 
          string moleculeElement = shouldCreateAbsolutePaths ? dtoObjectBase.Name : ObjectPathKeywords.MOLECULE;
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs:69]: Same here again.

**Review by rwmcintosh — CHANGES_REQUESTED** [review]
I think the use cases from this issue outlined by @PavelBal were pretty extensive. Did you verify that they all still work as they should. I think you did that a number of times.

If so, then I'd just remove this conditional statement that's not needed in the two places.

**Review by rwmcintosh — APPROVED** [review]

**Review by Yuri05 — APPROVED** [review]
