### PR TITLE
Fixes #1046 Context menu for passive transport exception

### LINKED ISSUE #1046: Context menu for passive transport exception
```
Application:
MoBi® 12.0.0

Failed to resolve an implementation of RemoveCommandFor`2
-----------------------------------------------------
Missing dependency.
Component OSPSuite.Presentation.MenuAndBars.IUICommand-MoBi.Presentation.UICommand.RemoveCommandFor`2-MoBi.Presentation.UICommand.RemoveCommandFor`2 has a dependency on MoBi.Presentation.Tasks.Interaction.IInteractionTasksForChildren`2[OSPSuite.Core.Domain.Builder.IBuildingBlock,OSPSuite.Core.Domain.Builder.TransportBuilder], which could not be resolved.
Make sure the dependency is correctly registered in the container as a service, or provided as inline argument.

Stack trace:

at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.DefaultGenericHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Resolve[TInterface]()
   at OSPSuite.Utility.Container.IoC.Resolve[TImplementationOfInterface]()
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Container.IoC.Resolve[TImplementationOfInterface]()
   at MoBi.Presentation.MenusAndBars.MenuBarItemExtensions.WithRemoveCommand[TParent,TChild](IMenuBarButton menuBarItem, TParent parent, TChild child) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\MenusAndBars\MenuBarItemExtensions.cs:line 15
   at MoBi.Presentation.MenusAndBars.ContextMenus.ContextMenuForPassiveTransportBuilder.CreateRemoveItemFor(TransportBuilder transportBuilder) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\MenusAndBars\ContextMenus\ContextMenuForPassiveTransportBuilder.cs:line 166
   at MoBi.Presentation.MenusAndBars.ContextMenus.ContextMenuForTransportBuilderBase.InitializeWith(TransportBuilderDTO dto, IPresenter presenter) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\MenusAndBars\ContextMenus\ContextMenuForPassiveTransportBuilder.cs:line 109
   at MoBi.Presentation.MenusAndBars.ContextMenus.ContextMenuSpecificationFactoryForPassiveTransportBuilder.CreateFor(TransportBuilderDTO transportBuilderDTO, IEditPassiveTransportBuildingBlockPresenter presenter) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\MenusAndBars\ContextMenus\ContextMenuForPassiveTransportBuilder.cs:line 54
   at MoBi.Presentation.MenusAndBars.ContextMenus.ContextMenuSpecificationFactoryForTransportBuilderBase`1.CreateFor(IViewItem viewItem, IPresenterWithContextMenu`1 presenter) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\MenusAndBars\ContextMenus\ContextMenuForPassiveTransportBuilder.cs:line 31
   at OSPSuite.Presentation.Presenters.ContextMenus.ContextMenuFactory`1.CreateFor(TObjectRequestingContextMenu objectRequestingContextMenu, IPresenterWithContextMenu`1 presenter)
   at MoBi.Presentation.Presenter.EditPassiveTransportBuildingBlockPresenter.ShowContextMenu(IViewItem objectRequestingPopup, Point popupLocation) in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\Presenter\EditPassiveTransportBuildingBlockPresenter.cs:line 89
   at MoBi.UI.Views.EditPassiveTransportBuildingBlockView.onGridViewMouseDown(MouseEventArgs e) in C:\repos\OSPSuite\MoBi\src\MoBi.UI\Views\EditPassiveTransportBuildingBlockView.cs:line 93
   at OSPSuite.UI.Views.BaseView.<>c__DisplayClass27_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Views.BaseView.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```
```

### PR DESCRIPTION
**Pull request by rwmcintosh**

### CODE REVIEW

File: src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForPassiveTransportBuilder.cs [hunk 1]
```diff
@@ -162,7 +162,7 @@ public ContextMenuForPassiveTransportBuilder(IMoBiContext context, IContainer co
 
       protected override IMenuBarItem CreateRemoveItemFor(TransportBuilder transportBuilder)
       {
-         var buildingBlock = transportBuilder.BuildingBlock;
+         var buildingBlock = transportBuilder.BuildingBlock as PassiveTransportBuildingBlock;
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForPassiveTransportBuilder.cs:165]: This used to be looked up like this:

```
var buildingblock = _context.CurrentProject.PassiveTransportCollection.FirstOrDefault(x => x.Contains(transportBuilder));
```

**Review by msevestre — APPROVED** [review]
maybe add a comment why this is required
