### PR TITLE
Fixes #264 directory issue when file does not exist

### LINKED ISSUE #264: 7.3 beta, portable MoBi version: Unhandled exception after trying to close MoBi
Using portable PK-Sim/MoBi: After sending a PK-Sim simulation to MoBi and subsequently directly closing  MoBi, I get an unhandled exception:

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\Open Systems Pharmacology\MoBi\7.3\ApplicationSettings.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at System.Xml.Linq.XDocument.Save(String fileName)
   at MoBi.Presentation.Serialization.Xml.SettingsPersistor`1.Save()
   at MoBi.Presentation.UICommand.ExitCommand.Execute()
   at MoBi.Presentation.Presenter.MoBiMainViewPresenter.FormClosing()
   at MoBi.UI.Views.MoBiMainView.mainViewFormClosing(Object sender, CancelEventArgs e)
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at System.Windows.Forms.Form.OnClosing(CancelEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at DevExpress.XtraBars.Ribbon.RibbonForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/MoBi.Presentation/Serialization/Xml/SettingsPersistor.cs [hunk 1]
```diff
@@ -36,11 +36,23 @@ public virtual void Save()
          {
             var serializer = _serializerRepository.SerializerFor(_settings);
             var xml = serializer.Serialize(_settings, serializationContext);
-            var doc = XDocument.Load(new StringReader(xml.ToString()));
-            doc.Save(SettingsFilePath);
+            saveSerializedSettingsToFile(xml);
          }
       }
 
+      private void saveSerializedSettingsToFile(XElement xml)
```
Comment (msevestre) [inline src/MoBi.Presentation/Serialization/Xml/SettingsPersistor.cs]: Just ensuring that the folder exists before saving. This is something that does not happen when installed with setup because folder is already created. 
There is absolutely no test on this behavior. This should be added when we have time for that

**Comment by msevestre** [comment]
@Yuri05 Please review
