### PR TITLE
1964 parameters from reactions are not listed in the possible referenced objects fix

### LINKED ISSUE #1964: Parameters from Reactions are not listed in the "Possible referenced objects"
[HallowModel_2017b_121.zip](https://github.com/user-attachments/files/21295433/HallowModel_2017b_121.zip)

See attached project. Some reactions have global parameters, e.g. `Sodium_Intake|Na_intake_rate`.

These parameters are not shown in any list of possible referenced objects when creating a formula:

Image

Expected behavior: reactions are shown in the root node, and can be expanded to show global parameters, similarly like in the simulations tree view:

Image

Same behavior in v11.

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #1964

# Description

Merge by module

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [ ] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image

# Questions (if appropriate):

### CODE REVIEW

**Review by rwmcintosh — CHANGES_REQUESTED** [review]
Undo the submodule changes

File: src/MoBi.Presentation/Presenter/SelectReferenceAtParameterPresenter.cs [hunk 1]
```diff
@@ -36,7 +36,7 @@ protected override void AddSpecificInitialObjects()
          if(_addTime)
             AddTimeReference();
          AddSpatialStructures();
-         AddReactions();
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/SelectReferenceAtParameterPresenter.cs:34]: I would just do one more thing before merging this. Can you check if this edition of the reactions should be used at all? I think all places where we are using `AddReactions` should be replaced with the new one.

I think it should be replaced everywhere. Eg, in this view where the tree view is built for molecule builder. 

Image

In other words, I think the old version `AddReactions` should be removed and this version used instead. And then I would just rename it `AddReactions`

**Review by rwmcintosh — APPROVED** [review]

File: src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs [hunk 2]
```diff
@@ -447,12 +459,8 @@ private IEnumerable<MoleculeBuilder> allMolecules
 
       protected void AddReactions()
       {
-         _view.AddNodes(getReactions.MapAllUsing(_referenceMapper));
-      }
-
-      private IEnumerable<ReactionBuilder> getReactions
-      {
-         get { return _buildingBlockRepository.ReactionBlockCollection.SelectMany(x => x).OrderBy(x => x.Name); }
+         var nodes = _buildingBlockRepository.ReactionBlockCollection.Select(x => _referenceMapper.MapFrom(x).WithText(x.DisplayName));
```
Comment (msevestre) [inline src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs]: @benjaperez1983 @rwmcintosh should not we always set the text to be the display name  in the referenceMapper? Why are we doing sthg special just for reactions?

**Review by msevestre — CHANGES_REQUESTED** [review]
question for me. Feels like the fix is in the wrong place

**Comment by rwmcintosh** [comment]
> question for me. Feels like the fix is in the wrong place

Well, the fix is not only the name, previously these were not grouped at all and all reactions from all modules were in a flat list.

File: src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs (hunk 2 above)
Comment (benjaperez1983) [reply src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs]: I Believe this is done as it is for AddSpatialStructores on Line 267:

"var nodes = spatialStructures.Select(x => _referenceMapper.MapFrom(x).WithText(x.DisplayName));"

Is there any particular reason why not to do it this way given then?

Comment (msevestre) [reply src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs]: >Is there any particular reason why not to do it this way given then?

what do you mean?

Comment (rwmcintosh) [reply src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs]: He's suggesting we move the naming into the `IObjectBaseDTOToReferenceNodeMapper`. See the `MapFrom` and add a check if the target is a building block, then we should use `DisplayName` always.

```
      public ITreeNode MapFrom(ObjectBaseDTO objectBaseDTO)
      {
         var node = new ReferenceNode(objectBaseDTO)
         {
            Icon = objectBaseDTO.Icon,
            GetChildren = x => _getChildren(x).Select(MapFrom).ToList()
         };

         if (objectBaseDTO.ObjectBase is BuildingBlock buildingBlock)
            node.Text = buildingBlock.DisplayName;
         
         return node;
      }
```

Comment (msevestre) [reply src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs]: yes that's what I am suggesting but what is @benjaperez1983 suggesting lol. If he suggests the same than yes

Comment (rwmcintosh) [reply src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs]: There's another location in this file where the `WithText` extension is used. @benjaperez1983  They can both be removed if the mapper uses the `DisplayName` internally.

Comment (benjaperez1983) [reply src/MoBi.Presentation/Presenter/SelectReferencePresenterBase.cs]: Exactly, it is either we do it for every case, or for none, to be consistent.
Will do it for all cases then and resolve the case.

**Comment by benjaperez1983** [comment]
@msevestre I believe all the comments are resolved. 
Whenever possible please take a look. 
Thanks
