### PR TITLE
fixes #566

### LINKED ISSUE #566: manual entry of molecule in importer not working
The manual entry of the molecule is not possible with the new version of core.

### PR DESCRIPTION
**Pull request by georgeDaskalakis**

### CODE REVIEW

File: src/MoBi.Presentation/Tasks/ObservedDataTask.cs [hunk 1]
```diff
@@ -495,7 +496,7 @@ private void addInfoToCategory(DimensionInfo.MetaDataCategory metaDataCategory,
             metaDataCategory.ListOfImages.Add(container.Name, icon.IconName);
       }
 
-      private DimensionInfo.MetaDataCategory createMetaDataCategory<T>(string categoryName, bool isMandatory = false, bool isListOfValuesFixed = false, Action<DimensionInfo.MetaDataCategory> fixedValuesRetriever = null, string description = null)
+      private DimensionInfo.MetaDataCategory createMetaDataCategory<T>(string categoryName, bool isMandatory = false, bool isListOfValuesFixed = false, Action<DimensionInfo.MetaDataCategory> fixedValuesRetriever = null, string description = null, bool allowsManualInput = false)
```
Comment (msevestre) [inline src/MoBi.Presentation/Tasks/ObservedDataTask.cs:499]: Is there a reasoin why we still have the name space DimensionInfo?

**Review by msevestre — CHANGES_REQUESTED** [review]
one question. I think this should be removed (namespace DimensionInfo)

File: src/MoBi.Presentation/Tasks/ObservedDataTask.cs (hunk 1 above)
Comment (msevestre) [reply src/MoBi.Presentation/Tasks/ObservedDataTask.cs:499]: well at least in core :)
