### PR TITLE
Fixes #2166 Simulation cannot be closed due to invalid output intervals

### LINKED ISSUE #2166: Simulation cannot be closed due to invalid output intervals
Simulation view becomes inactive and cannot be closed due to invalid OutputIntervals

how to reproduce:
- enter an invalid output interval, e.g. 48h to 24h
- ignore the red crosses indicating the error and run the simulation by pressing F5
- view will switch from Parameters tab to Results tab and error message will pop up
- returning back to parameters tab is not possible. neither is closing the simulation

now 3 possibilities:
1) try to close the simulation by e.g. "close all documents" --> watch the blue circle of death for several minutes --> simulation view is still blocked
2) close project (not MoBi) --> the simulation view will stay --> reopening project doesn't help
3) save project, exit mobi and reopen project --> all good, change the output interval

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2166

# Description
There's some rework of the validation and some additional validation done. Also, we do not show results tab on a simulation unless the simulation was completed successfully.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/EditSimulationPresenter.cs [hunk 1]
```diff
@@ -230,7 +230,7 @@ public void Handle(SimulationRunFinishedEvent eventToHandle)
 
          _view.SetParametersTabEnabled(true);
 
-         if (!_view.ShowsResults)
+         if (!_view.ShowsResults && eventToHandle.Success)
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/EditSimulationPresenter.cs:233]: I added this first to only prevent the tab from switching when the simulation fails. The symptom was that the validation error is being shown in the parameter screen, and you cannot switch the tabs when that happens, but you can programmatically switch. When that happens you cannot switch back.

File: src/MoBi.UI/Views/EditOutputSchemaView.cs [hunk 2]
```diff
@@ -33,7 +33,7 @@ public EditOutputSchemaView()
 
       public override void InitializeBinding()
       {
-         _gridViewBinder = new GridViewBinder<OutputIntervalDTO>(gridViewIntervals) { BindingMode = BindingMode.OneWay, ValidationMode = ValidationMode.LeavingRow };
+         _gridViewBinder = new GridViewBinder<OutputIntervalDTO>(gridViewIntervals) { BindingMode = BindingMode.OneWay };
```
Comment (rwmcintosh) [inline src/MoBi.UI/Views/EditOutputSchemaView.cs:36]: It's a bit less convenient without `LeavingRow`, but with it, you can create the invalid state, and we should prevent the parameter from being changed to create an invalid output interval.

File: src/MoBi.Presentation/Presenter/EditOutputSchemaPresenter.cs [hunk 3]
```diff
@@ -77,14 +81,60 @@ public void RemoveOutputInterval(OutputIntervalDTO outputIntervalDTO)
          bindToView();
       }
 
-      public void SetParameterUnit(IParameterDTO parameterDTO, Unit newUnit)
+      public void SetParameterUnit(IParameterDTO parameterDTO, Unit newUnit, OutputIntervalDTO outputIntervalDTO)
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/EditOutputSchemaPresenter.cs:84]: The UI validation doesn't work as well with the combobox, so in the presenter we test for invalid unit changes and create a dialog to inform the user.

File: src/MoBi.UI/Views/EditOutputSchemaView.cs (hunk 2 above)
Comment (Yuri05) [reply src/MoBi.UI/Views/EditOutputSchemaView.cs:36]: With this change, what will be the validation mode? LeavingCell?

Comment (rwmcintosh) [reply src/MoBi.UI/Views/EditOutputSchemaView.cs:36]: Yeah, the standard, when you leave the cell

Comment (Yuri05) [reply src/MoBi.UI/Views/EditOutputSchemaView.cs:36]: Meaning that we will need to edit start/end time always in the "correct" order.
E.g. if I add a second time interval and would like to change it from [0h .. 24h] to e.g. [25h .. 50h] - I would need to change the **end time** first, and then a start time. Little bit annoying, but I can live with it.

Image

Comment (rwmcintosh) [reply src/MoBi.UI/Views/EditOutputSchemaView.cs:36]: Yes, that's right. A little less convenient, but better than finding this other bug where the user could not do anything but kill the process.

Comment (Yuri05) [reply src/MoBi.UI/Views/EditOutputSchemaView.cs:36]: Agree

**Review by Yuri05 — APPROVED** [review]
