### PR TITLE
Fixes #1085 Error when modifying a table formula with x argument

### LINKED ISSUE #1085: Error when modifying a table formula with x argument
When trying to change path to table object or to a-argument of a table formula with x argument, an error is thrown:

image

Application:
MoBi® 12.0.45

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Presenter.EditTableFormulaWithXArgumentFormulaPresenter.selectFormulaUsablePath(Func`2 predicate, String caption)
   at MoBi.Presentation.Presenter.EditTableFormulaWithXArgumentFormulaPresenter.SetXArgumentFormulaPath()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

Already in v11.

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1085

# Description
In this case, we are editing the formula from the formula cache and do not have the context of what is using the formula. There seems to be some provisions for that and I just made some more so the application will not crash.

I'm not sure if there's another way that would be preferred. Essentially, if you edit from the formula cache, you lose the ability to specify relative paths (it seems). It seems to make sense to me.

For now, I would like a quick comment on whether this approach makes sense, then I'll add some tests for it.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/EditTableFormulaWithXArgumentFormulaPresenter.cs [hunk 1]
```diff
@@ -87,8 +88,8 @@ private FormulaUsablePath selectFormulaUsablePath(Func<IObjectBase, bool> predic
       {
          using (var presenter = _applicationController.Start<ISelectFormulaUsablePathPresenter>())
          {
-            var referencePresenter = _selectReferencePresenterFactory.ReferenceAtParameterFor(UsingObject.ParentContainer);
-            presenter.Init(predicate, UsingObject, new[] {UsingObject.RootContainer}, caption, referencePresenter);
+            var referencePresenter = _selectReferencePresenterFactory.ReferenceAtParameterFor(UsingObject?.ParentContainer);
```
Comment (msevestre) [inline src/MoBi.Presentation/Presenter/EditTableFormulaWithXArgumentFormulaPresenter.cs:91]: Why is UsingObject null? isn't it the problem?

**Review by msevestre — APPROVED** [review]
looks good but I am wondering why we are  guarding ourselves against an object that is null that maybe should not be null in the first place. Should the caller be changed?
Approved otherwise if this makes sense
