### PR TITLE
Fixes #1152 crash when selecting a neighbor in a neighborhood after opening the diagram

### LINKED ISSUE #1152: Crash when selecting a neighbor in a neighborhood after opening the diagram

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1152

# Description
When first or second neighbor nodes are selected in a spatial structure, the diagram manager does not handle a case where the EntitySelectedEvent is built without an ObjectBase.

I chose not to publish the event in this case, but alternatively, we could handle the case where the event is handled without ObjectBase

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/BaseDiagram/MoBiBaseDiagramPresenter.cs [hunk 1]
```diff
@@ -102,13 +98,16 @@ public PointF CurrentInsertLocation
       /// </summary>
       public void Handle(EntitySelectedEvent eventToHandle)
       {
-         if (DiagramManager == null) return;
-         if (!DiagramManager.MustHandleExisting(eventToHandle.ObjectBase.Id)) return;
+         if (DiagramManager == null)
+            return;
 
-         IBaseNode baseNode = DiagramModel.GetNode(eventToHandle.ObjectBase.Id);
+         if (!DiagramManager.MustHandleExisting(eventToHandle.ObjectBase.Id))
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/BaseDiagram/MoBiBaseDiagramPresenter.cs:104]: We could handle this event without ObjectBase here, but I prevent the event from being raised in the first place.

File: src/MoBi.Presentation/Presenter/HierarchicalStructurePresenter.cs [hunk 2]
```diff
@@ -111,7 +111,10 @@ public virtual void Select(ObjectBaseDTO objectBaseDTO)
 
       private void raiseEntitySelectedEvent(ObjectBaseDTO objectBaseDTO)
       {
-         _context.PublishEvent(new EntitySelectedEvent(objectBaseDTO.ObjectBase, this));
+         // First and second neighbor node selections should not trigger an EntitySelectedEvent
+         // because the are not ObjectBase
+         if(objectBaseDTO.ObjectBase != null)
+            _context.PublishEvent(new EntitySelectedEvent(objectBaseDTO.ObjectBase, this));
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/HierarchicalStructurePresenter.cs:117]: Probably better to not publish the event since no other presenters can handle it I guess
