### PR TITLE
Mobi r fixes

### LINKED ISSUE #2337: `CreateIndividual(IndividualCharacteristics individualCharacteristics);` should require a "name" argument
All BBs loaded from a project have names. Therefore, when creating a new BB from R, it should also be possible to specify its name.

### LINKED ISSUE #2338: Use more generic SpatialStructure instead of MoBiSpatialStructure
`string[] ExtendInitialConditions(InitialConditionsBuildingBlock buildingBlock, MoBiSpatialStructure spatialStructure, MoleculeBuildingBlock moleculeBuildingBlock, params string[] moleculeNames);`

Expects `MoBiSpatialStructure`. This works if I load a spatial structure from a MoBi project. But when I load a simulation from PKML that was exported from PK-Sim, and retrieve the spatial structure BB from there, its just `SpatialStructure` and the method fails with 

 
```
Could not find a suitable instance method ExtendInitialConditions on type MoBi.R.Services.InitialConditionsTask for method parameters InitialConditionsBuildingBlock, SpatialStructure, MoleculeBuildingBlock, String[]
```
I think it should expect SpatialStructure instead of MoBìSpatialStructure?

Same for AddLocalMoleculeParameters from the ParameterValuesTask

### LINKED ISSUE #2339: Implement All{Property}From methods for IndividualTask and InitialConditionsTask
These getters are missing from IIndividualTask and IInitialConditionsTask.

```
   string[] AllPathsFrom(TBuildingBlock buildingBlock);
   double[] AllValuesFrom(TBuildingBlock buildingBlock, params string[] paths);
   string[] AllDimensionsFrom(TBuildingBlock buildingBlock, params string[] paths);
   string[] AllUnitsFrom(TBuildingBlock buildingBlock, params string[] paths);
```

### LINKED ISSUE #2340: Export building block as pkml in MoBi.R
For each of the building block tasks, implement a ExportToPKML method that accepts a file path and the building block of the task.

### PR DESCRIPTION
**Pull request by rwmcintosh**
I implemented these issues in one PR because they all touch the same files and I didn't want to deal with the merge conflicts. It's a bit confusing to review this way though so I probably won't do it again.

Fixes #2338
Fixes #2337
Fixes #2339
Fixes #2340

## Summary by CodeRabbit

* **New Features**
  * PKML export for expression profiles, individuals, initial conditions and parameter values
  * Improved building-block data extraction: unified APIs to get paths, values, dimensions and units

* **Chores**
  * Added a Windows helper script to create local packages for development/testing

* **Tests**
  * Added integration tests verifying PKML exports produce valid XML files

### CODE REVIEW

File: src/MoBi.R/Services/IndividualTask.cs [hunk 1]
```diff
@@ -34,13 +36,15 @@ public IndividualTask(IXmlSerializationService xmlSerializationService, IMoBiPro
...
+   public IndividualBuildingBlock CreateIndividual(IndividualCharacteristics individualCharacteristics, string name)
    {
       LoadPKSimAssembly();
 
       var serializedIndividual = ExecuteMethod(GetMethod("PKSim.R.Exchange.BuildingBlockCreator", "CreateIndividual"), [individualCharacteristics]) as string;
 
-      return _xmlSerializationService.Deserialize<IndividualBuildingBlock>(serializedIndividual, _projectRetriever.Current);
+      var buildingBlock = _xmlSerializationService.Deserialize<IndividualBuildingBlock>(serializedIndividual, _projectRetriever.Current);
+      buildingBlock.Name = name;
+      return buildingBlock;
```
Comment (rwmcintosh) [inline src/MoBi.R/Services/IndividualTask.cs:47]: Add name to the building block #2337

File: src/MoBi.R/Services/IndividualTask.cs [hunk 2]
```diff
@@ -55,10 +59,13 @@ public void SetIndividualParameter(IndividualBuildingBlock buildingBlock, string
...
-      macroCommand.AddRange(quantityPaths.Select((quantityPath, i) => UpdateValueCommandFor<IndividualBuildingBlock, IndividualParameter>(buildingBlock, quantityPath, quantityValues[i])));
+      macroCommand.AddRange(quantityPaths.Select((quantityPath, i) => UpdateValueCommandFor(buildingBlock, quantityPath, quantityValues[i])));
 
       _context.AddToHistory(macroCommand.RunCommand(_context));
    }
 
    public void SetIndividualParameter(IndividualBuildingBlock buildingBlock, string quantityPath, double quantityValue) => SetIndividualParameter(buildingBlock, [quantityPath], [quantityValue]);
+
+   public void ExportToPKML(IndividualBuildingBlock buildingBlock, string filePath) =>
+      _xmlSerializationService.SerializeModelPart(buildingBlock).PermissiveSave(filePath);
```
Comment (rwmcintosh) [inline src/MoBi.R/Services/IndividualTask.cs:70]: #2340

File: src/MoBi.R/Services/InitialConditionsTask.cs [hunk 3]
```diff
@@ -15,7 +18,7 @@ public interface IInitialConditionsTask : IPathAndValuesTask<InitialConditionsBu
 {
    void DeleteInitialConditions(InitialConditionsBuildingBlock buildingBlock, params string[] pathsToDelete);
 
-   string[] ExtendInitialConditions(InitialConditionsBuildingBlock buildingBlock, MoBiSpatialStructure spatialStructure, MoleculeBuildingBlock moleculeBuildingBlock, params string[] moleculeNames);
+   string[] ExtendInitialConditions(InitialConditionsBuildingBlock buildingBlock, SpatialStructure spatialStructure, MoleculeBuildingBlock moleculeBuildingBlock, params string[] moleculeNames);
```
Comment (rwmcintosh) [inline src/MoBi.R/Services/InitialConditionsTask.cs:21]: #2338

File: rakefile.rb
Comment (rwmcintosh) [inline rakefile.rb:1]: I added these helpers to make it easier and faster to build and test MoBi.R changes in OSPSuite-R. I have a similar update for PK-Sim.

File: src/MoBi.R/Extensions/PathAndValueEntityBuildingBlockExtensions.cs
Comment (rwmcintosh) [inline src/MoBi.R/Extensions/PathAndValueEntityBuildingBlockExtensions.cs:1]: This was moved from the task so that it can be reused more easily

**Review by Yuri05 — APPROVED** [review]
