### PR TITLE
Fixes #1462

### LINKED ISSUE #1462: MoBi crashes with a wrongly set up event
In the attached project, there is an event that should increment the value of a variable `eventCounter` every time the event is fired. The checkbox "Use assignment as value" has wrongly been set to "false".

image

When trying to run the simulation with "Plot parameter" selected for `eventCounter` (and only then!), MoBi silently crashes.
[endless-event.zip](https://github.com/user-attachments/files/16508172/endless-event.zip)

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1462 Crash with wrongly set up event

# Description
Circular reference checking during building block construction

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image
image

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/DTO/EventAssignmentBuilderDTO.cs [hunk 1]
```diff
@@ -17,6 +21,73 @@ public EventAssignmentBuilderDTO(EventAssignmentBuilder eventAssignmentBuilder)
...
+      {
+         var assignmentBuilder = dto._eventAssignmentBuilder;
+         var assignmentPath = assignmentBuilder.ObjectPath;
+         var formulaPaths = formulaDTO.ObjectPaths.Select(x => x.FormulaUsablePath).ToList();
+
+         if (!canReferToAssignmentTarget(assignmentBuilder.UseAsValue, assignmentPath, formulaPaths))
+            return false;
+
+         return formulaPathsReferToAssignmentTarget(assignmentPath, assignmentBuilder, formulaPaths);
+      }
```
Comment (Yuri05) [inline src/MoBi.Presentation/DTO/EventAssignmentBuilderDTO.cs:44]: minor issue: the 3 `formulaRefersToXYZ `functions could be simplified a bit by passing directly `dto._eventAssignmentBuilder` as the 1st argument and extracting the last 3 code lines into a separate function.

File: src/MoBi.Presentation/Presenter/EditAssignmentBuilderPresenter.cs [hunk 2]
```diff
@@ -112,6 +115,16 @@ public void SelectPath()
...
+      private ICache<IObjectBase, string> getForbiddenAssignees()
+      {
+         var cache = new Cache<IObjectBase, string>();
+         if (_eventAssignmentBuilder.UseAsValue || _eventAssignmentBuilder.Formula == null)
+            return cache;
+
+         _eventAssignmentBuilder.Formula.ObjectPaths.Select(x => x.TryResolve<IUsingFormula>(_eventAssignmentBuilder)).Each(x => cache.Add(x, AppConstants.Captions.AssigningFormulaCreatesCircularReference));
+         return cache;
+      }
+
```
Comment (Yuri05) [inline src/MoBi.Presentation/Presenter/EditAssignmentBuilderPresenter.cs:127]: seems to be the same function as in **EditEventBuilderPresenter** - could be defined e.g. as extension method of **EventAssignmentBuilder**?

File: tests/MoBi.Tests/Presentation/concern_for_EventAssignmentBuilderDTO.cs
Comment (Yuri05) [inline tests/MoBi.Tests/Presentation/concern_for_EventAssignmentBuilderDTO.cs:1]: why not naming the file **EventAssignmentBuilderDTOSpecs.cs**?

**Review by Yuri05 — APPROVED** [review]
