### PR TITLE
#1817 remove simulation result

### LINKED ISSUE #1817: Deleting simulation results does not work
Run simulations couple of times and try to delete a simulation result:

Image

Nothing happens.

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #1817

# Description

Remove SImulation result does not work.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForHistoricalResultsNode.cs [hunk 1]
```diff
@@ -59,8 +59,12 @@ public IContextMenu InitializeWith(DataRepository dataRepository, IMoBiSimulatio
             .WithIcon(ApplicationIcons.Rename)
             .WithCommand(command));
 
+         var removeResultsCommand = _container.Resolve<RemoveSimulationResultCommand>();
+         removeResultsCommand.Subject = dataRepository;
+         removeResultsCommand.Simulation = simulation;
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForHistoricalResultsNode.cs]: See on line 49 the same pattern except initializing the properties is done with a method `InitializeWith`. It's exactly what you have, but in a method.

File: src/MoBi.Presentation/Tasks/ObservedDataTask.cs [hunk 2]
```diff
@@ -165,6 +167,15 @@ private static MoBiMacroCommand deleteAllResultsFromSimulationCommand(IMoBiSimul
          return macroCommand;
       }
 
+      public void DeleteResultsFromSimulationCommand(IMoBiSimulation simulation, DataRepository dataRepository)
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Tasks/ObservedDataTask.cs]: Rename to drop `Command` from the name. The task is using a command, but the action is `DeleteResultsFromSimulation`

File: src/MoBi.Presentation/UICommand/ImportDataRepositoryUICommand.cs [hunk 3]
```diff
@@ -36,6 +37,22 @@ public void Execute()
       }
    }
 
+   internal class RemoveSimulationResultCommand : ObjectUICommand<DataRepository>
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/UICommand/ImportDataRepositoryUICommand.cs]: I know there are some UI commands without it, but I would prefer a UI command has a name like `RemoveSimulationResultUICommand`. To clarify that it's a UI command when your auto-complete is activated.

File: src/MoBi.Presentation/Tasks/ObservedDataTask.cs [hunk 4]
```diff
@@ -165,6 +167,15 @@ private static MoBiMacroCommand deleteAllResultsFromSimulationCommand(IMoBiSimul
...
+      {
+         var viewResult = _dialogCreator.MessageBoxYesNo(AppConstants.Dialog.RemoveSimulationResultsFromSimulation(dataRepository.Name, simulation.Name));
+         if (viewResult == ViewResult.No)
+            return;
+
+         _context.AddToHistory(new RemoveHistoricResultFromSimulationCommand(simulation, dataRepository).RunCommand(_context));
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Tasks/ObservedDataTask.cs:176]: That needs a test for the `viewResult`

**Review by rwmcintosh — CHANGES_REQUESTED** [review]

**Review by rwmcintosh — APPROVED** [review]
