### PR TITLE
Fixes #1468

### LINKED ISSUE #1468: Neighborhood creation - path created for a neighbor contains "Organism" twice
[PregnancyV1.zip](https://github.com/user-attachments/files/16509992/PregnancyV1.zip)

Module "Pregnancy V2", open the spatial structure BB, create new neighborhood. Select "Pregnancy V2|Endometrium|Interstitial" as a neighbor. The created path is `Organism|Organism|Endometrium|Interstitial`,  which is wrong (should be `Organism|Endometrium|Interstitial`

image

### PR DESCRIPTION
**Pull request by msevestre**
Fixes #1468

# Description

MAke sure we do not add the path manually when creating an absolute path

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [ ] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs [hunk 1]
```diff
@@ -47,9 +47,7 @@ private void onSelectedContainerPathChanged(IEntity entity, ObjectPath container
          if (container.Mode != ContainerMode.Physical)
             return;
 
-         var parentPath = container.RootContainer.ParentPath?.Clone<ObjectPath>() ?? new ObjectPath();
```
Comment (msevestre) [inline src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs:50]: We were adding the patent path explicitly . No need to since we assume the path was already created as expected

Comment (msevestre) [reply src/MoBi.Presentation/Presenter/SelectNeighborPathPresenter.cs:50]: now I just create the absolute path right in the selection so that we are in control

**Review by Yuri05 — APPROVED** [review]

**Comment by rwmcintosh** [comment]
Something is wrong after this merge. I can't run all the tests locally or on Appveyor. I will look at it again monday.

**Review by rwmcintosh — APPROVED** [review]
