### PR TITLE
Fixes #1702 "Time" not recognized in newly build formula

### LINKED ISSUE #1702: V12 beta: Simulation time parameter path "Time" not recognized in newly build formula
In the attached MoBi project (tstAdmin.mbp3 in "tstAdminError.zip") there is an SC administration event which was built from an IV administration event imported from PK-Sim.
[tstAdminError.zip](https://github.com/user-attachments/files/18083978/tstAdminError.zip)

Everything works fine if one uses within the Application_StartEvent (module "AdminEvents_SC_humanTwoCompartments") the formula "ClonedRate" which was generated by cloning the formula "ApplicationRate_Intravenous", see screenshot: 

clonedEq

However, if one generates a formula from scratch, formula "ApplicationRate_SC", and uses this one within the Application_StartEvent (project "tstAdminError.mbp3" in "tstAdminError.zip" & see screenshot), 

new

the simulation cannot be generated. The error message states that "an entity with path 'Time' that cannot be found", see screenshot: 

error

To me the formula "ClonedRate" and "ApplicationRate_SC" look equal, especially the path to Time is just "Time" in both cases.
 So, why does the newly build formula "ApplicationRate_SC" does not work?

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1702

# Description
A `FormulaUsablePath` has to be converted to a `TimePath` if the dimension and path are set up correctly through the editor. That's because `TimePath` overrides the `Resolve` method of `ObjectPath`

The reverse is also true if a dimension or path is adjusted on a `TimePath`

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Tasks/MoBiFormulaTask.cs [hunk 1]
```diff
@@ -160,20 +173,47 @@ public IMoBiCommand RemoveFormulaUsablePath(IFormula formula, FormulaUsablePath
...
+         macroCommand.Add(getRemoveFormulaUsablePathCommand(formula, oldPath, buildingBlock));
+         macroCommand.Add(getAddFormulaUsablePathCommand(formula, newPath, buildingBlock));
+         return macroCommand;
       }
 
+      private bool isTimePathAndDimension(ObjectPath newPath, IDimension dimension) => dimension.Equals(timeDimension) && newPath.PathAsString.Equals(Constants.TIME);
+
+      public IMoBiCommand AddFormulaUsablePath(IFormula formula, FormulaUsablePath path, IBuildingBlock buildingBlock) => getAddFormulaUsablePathCommand(formula, path, buildingBlock).RunCommand(_context);
+
+      private static AddFormulaUsablePathCommand getAddFormulaUsablePathCommand(IFormula formula, FormulaUsablePath path, IBuildingBlock buildingBlock) => new AddFormulaUsablePathCommand(formula, path, buildingBlock);
```
Comment (msevestre) [inline src/MoBi.Presentation/Tasks/MoBiFormulaTask.cs:211]: why these methods? they are just doing new with the parameter ? looking at the code, I thoight something big was happening and in fact it just creates an instance. Doyou think it helps readability?

Comment (rwmcintosh) [reply src/MoBi.Presentation/Tasks/MoBiFormulaTask.cs:211]: Yeah, could do without it. It didn't really help with reuse since the only thing was creating the command

File: src/MoBi.Presentation/Tasks/MoBiFormulaTask.cs [hunk 2]
```diff
@@ -131,21 +134,31 @@ public IMoBiCommand SetFormulaString(FormulaWithFormulaString formula, string ne
...
-         return new UpdateDimensionOfFormulaUsablePathCommand(newDimension, formula, alias, buildingBlock).RunCommand(_context);
-      }
+         IMoBiCommand command;
+         var formulaUsablePath = formula.FormulaUsablePathBy(alias);
+         if (isTimePathAndDimension(formulaUsablePath, newDimension))
+         {
+            var timePath = _context.ObjectPathFactory.CreateTimePath(timeDimension).WithAlias(formulaUsablePath.Alias);
+            command = swapFormulaUsablePaths(formula, formulaUsablePath, timePath, buildingBlock);
+         }
+         else if (formulaUsablePath is TimePath)
```
[the remark this answers is not in the document]
Comment (rwmcintosh) [reply src/MoBi.Presentation/Tasks/MoBiFormulaTask.cs:149]: comment added. I suppose it's not only the editing of an existing path, but also, when someone enters a new path, they pick the right dimension and the right path, but it still won't work.

**Review by Yuri05 — APPROVED** [review]
