### PR TITLE
2193 create a simulation from simulation configuration

### LINKED ISSUE #2193: Create a simulation from simulation configuration
MoBi.R.Services.SimulationFactory.CreateSimulation() has the following signature:
 

string simulationName, IReadOnlyList<RModuleConfiguration> moduleConfigurations,
         IReadOnlyList<ExpressionProfileBuildingBlock> expressionProfiles,
         IndividualBuildingBlock individual)
 
The problem is that when I pass an array of something that is not a base type from R, it arrives as aob Object[] array. so I cannot create an array (or a list) of expression profiles, I get the error:
 
Could not find a suitable instance method CreateSimulationFrom on type MoBi.R.Services.SimulationTask for method parameters String, Object[], Object[], IndividualBuildingBlock

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #2193 

# Description

Create simulation from configuration for MoBi.R

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Integration tests
- [x] Unit tests
- [ ] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

## Summary by CodeRabbit

* **New Features**
  * Simulation creation now returns a structured result (simulation + warnings/errors).
  * New request-driven API to build simulations from module configurations, expression profiles, and an individual.
  * Added a lightweight simulation wrapper exposing core simulation details.

* **Refactor**
  * Creation and factory flows now include validation results and clearer failure reporting.

* **Chores**
  * Calculation-method repository seeded with default entries at startup.

* **Breaking Changes**
  * Legacy project-level simulation lookup APIs removed/replaced.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/MoBi.R/Services/SimulationFactory.cs [hunk 1]
```diff
@@ -1,63 +1,100 @@
...
+         {
+            return createResultWithMessages(e);
+         }
+         catch (Exception e)
+         {
+            return new CreateSimulationResult(null, Enumerable.Empty<string>(), new[] { e.Message });
+         }
+      }
+
+      private static CreateSimulationResult createResultWithMessages(ValidationFailedMoBiException e)
```
[the remark this answers is not in the document]
Comment (benjaperez1983) [reply src/MoBi.R/Services/SimulationFactory.cs]: private methods follow this convention to our codebase

File: src/MoBi.R/AllCalculationMethods.pkml
Comment (Yuri05) [inline src/MoBi.R/AllCalculationMethods.pkml:1]: why adding a duplicate of **src/Data/AllCalculationMethods.pkml** here and in the **MoBi.R.Tests** project?

**Comment by msevestre** [comment]
@coderabbitai review

File: src/MoBi.R/AllCalculationMethods.pkml
Comment (benjaperez1983) [reply src/MoBi.R/AllCalculationMethods.pkml:1]: Well both need this in order not to fail the registration and after that, to be able to fully create the simulation. 
It needs to be copied to the same path as the libraries are, since by default that`s where the registration picks it up to load the calculation methods.

Comment (Yuri05) [reply src/MoBi.R/AllCalculationMethods.pkml:1]: That's fine, but **adding to GitHub** is not required, correct?
Let's add to **.gitignore** then.

Comment (rwmcintosh) [reply src/MoBi.R/AllCalculationMethods.pkml:1]: yes, remove this copy completely and `Add as link` from the `src\Data` folder

Image

File: src/MoBi.R/MoBi.R.csproj [hunk 2]
```diff
@@ -19,15 +19,17 @@
...
         <Pack>True</Pack>
         <PackagePath></PackagePath>
      </None>
   </ItemGroup>
 
+  <ItemGroup>
+    <None Update="AllCalculationMethods.pkml">
+      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
+    </None>
+  </ItemGroup>
```
Comment (rwmcintosh) [inline src/MoBi.R/MoBi.R.csproj]: That should be a link to `src\Data\AllCalculationMethods.pkml`

File: src/MoBi.Core/Domain/Model/SimulationAndValidationResult.cs [hunk 3]
```diff
@@ -0,0 +1,21 @@
+﻿using OSPSuite.Core.Domain;
+
+namespace MoBi.Core.Domain.Model
+{
+   public sealed class SimulationAndValidationResult
```
Comment (rwmcintosh) [inline src/MoBi.Core/Domain/Model/SimulationAndValidationResult.cs]: why is it sealed?

File: src/MoBi.R/Services/SimulationFactory.cs [hunk 4]
```diff
@@ -1,63 +1,100 @@
...
-         configuration.ExpressionProfiles.Each(simulationConfiguration.AddExpressionProfile);
-
-         simulationConfiguration.Individual = configuration.Individual;
+         typedExpressionProfiles.Each(simulationConfiguration.AddExpressionProfile);
 
+         simulationConfiguration.Individual = individual;
          simulationConfiguration.ShouldValidate = true;
+         try
+         {
+            var simulationWithValidation = _simulationFactory.CreateSimulationAndValidationResult(simulationConfiguration, simulationName);
```
Comment (rwmcintosh) [inline src/MoBi.R/Services/SimulationFactory.cs]: use the deconstructor

```
var (simulation, validationResult) = _simulationFactory.CreateSimulationAndValidationResult(simulationConfiguration, simulationName);
```

File: src/MoBi.Core/Domain/Services/SimulationFactory.cs [hunk 5]
```diff
@@ -26,7 +26,7 @@ public interface ISimulationFactory
       /// </summary>
       IMoBiSimulation Create();
 
-      IMoBiSimulation CreateSimulationAndValidate(SimulationConfiguration configurationReferencingBuildingBlocks, string simulationName);
+      SimulationAndValidationResult CreateSimulationAndValidationResult(SimulationConfiguration configurationReferencingBuildingBlocks, string simulationName);
```
Comment (rwmcintosh) [inline src/MoBi.Core/Domain/Services/SimulationFactory.cs]: I get why you changed it, but I think the purpose of the method is still to `CreateSimulationAndValidate` and I'm in favor of changing the name back to the original even though the return type has changed to include the validation result

File: src/MoBi.Core/Exceptions/MoBiException.cs
Comment (rwmcintosh) [inline src/MoBi.Core/Exceptions/MoBiException.cs:1]: run ReSharper in this file (and others too if you haven't)

File: src/MoBi.R/Domain/CreateSimulationResult.cs [hunk 6]
```diff
@@ -0,0 +1,21 @@
+using OSPSuite.R.Domain;
+using System;
+using System.Collections.Generic;
+using System.Linq;
+
+namespace MoBi.R.Domain
+{
+   public sealed class CreateSimulationResult
```
Comment (rwmcintosh) [inline src/MoBi.R/Domain/CreateSimulationResult.cs]: Why sealed?

File: src/MoBi.R/Services/SimulationTask.cs [hunk 7]
```diff
@@ -1,23 +1,19 @@
...
 namespace MoBi.R.Services
 {
    public interface ISimulationTask
    {
-      Simulation CreateSimulationFrom(SimulationConfiguration simulationConfiguration, string simulationName);
-
-      SimulationConfiguration CreateConfiguration(IReadOnlyList<ModuleConfiguration> moduleConfigurations = null,
-         IReadOnlyList<ExpressionProfileBuildingBlock> expressionProfiles = null,
-         IndividualBuildingBlock individual = null);
+      CreateSimulationResult CreateSimulationResultsFrom(string simulationName, SimulationRequest request);
```
Comment (rwmcintosh) [inline src/MoBi.R/Services/SimulationTask.cs]: The naming is confusing here for me. The method and the class `CreateSimulationResult` because you aren't getting simulation results like from running a simulation.

Maybe `SimulationCreationResult` for the class and I would call the method `CreateSimulationFrom` because the main purpose is the simulation.

**Review by rwmcintosh — CHANGES_REQUESTED** [review]
I'll take another look again after these comments are addressed. Some are must, some naming stuff, I'm not so sure I have it right.

File: src/MoBi.Core/Exceptions/MoBiException.cs [hunk 8]
```diff
@@ -1,8 +1,10 @@
-﻿using System;
-using MoBi.Assets;
+﻿using MoBi.Assets;
 using OSPSuite.Assets;
 using OSPSuite.Core.Domain;
 using OSPSuite.Utility.Exceptions;
+using System;
+using System.Collections.Generic;
+using System.Linq;
```
[the remark this answers is not in the document]
Comment (Yuri05) [reply src/MoBi.Core/Exceptions/MoBiException.cs]: @copilot seriously? 😆

[the remark this answers is not in the document]
Comment (rwmcintosh) [reply src/MoBi.Core/Exceptions/MoBiException.cs]: That's what ReSharper also does. This is C# common practice.

[the remark this answers is not in the document]
Comment (Yuri05) [reply src/MoBi.Core/Exceptions/MoBiException.cs]: Never noticed this, lol. I absolutely don't care 😄

File: src/MoBi.R/AllCalculationMethods.pkml
Comment (rwmcintosh) [inline src/MoBi.R/AllCalculationMethods.pkml:1]: This is still incorrect. The file should be removed from the file system and the link to src\Data one should be used. The reason is that we update the file occasionally from PK-Sim and it should only be updated in one place.

File: src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs [hunk 9]
```diff
@@ -142,8 +142,8 @@ private IMoBiSimulation createSimulation()
             if (simulationConfiguration == null)
                return null;
 
-
-            return _simulationFactory.CreateSimulationAndValidate(simulationConfiguration, presenter.SimulationName);
+            var (simulation, _) = _simulationFactory.CreateSimulationAndValidate(simulationConfiguration, presenter.SimulationName);
+            return simulation;
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Tasks/Interaction/InteractionTasksForSimulation.cs]: You can do this all in one line without the variable.

`return _simulationFactory.CreateSimulationAndValidate(simulationConfiguration, presenter.SimulationName).Simulation`

File: src/MoBi.R/Services/SimulationTask.cs [hunk 10]
```diff
@@ -58,17 +43,23 @@ public ModuleConfiguration CreateModuleConfiguration(Module module,
...
 
-      public Simulation CreateSimulationFrom(SimulationConfiguration simulationConfiguration, string simulationName) => 
-         _simulationFactory.CreateSimulation(simulationConfiguration, simulationName);
+      public SimulationCreationResult CreateSimulationAndValidateFrom(string simulationName, SimulationRequest request)
+      {
+         var modulesArray = request?.ModuleConfigurations?.ToArray() ?? Array.Empty<ModuleConfiguration>();
+         var expressionsArray = request?.ExpressionProfiles?.ToArray() ?? Array.Empty<ExpressionProfileBuildingBlock>();
+
+         var createSimResults = _simulationFactory.CreateSimulationFrom(simulationName, modulesArray, expressionsArray, request?.Individual);
+         return createSimResults;
```
Comment (rwmcintosh) [inline src/MoBi.R/Services/SimulationTask.cs]: just return without creating a `var`

File: src/MoBi.R/Services/SimulationFactory.cs [hunk 11]
```diff
@@ -1,63 +1,99 @@
...
+            .Where(m => m.NotificationType == NotificationType.Warning)
+            .Select(m => m.Text)
+            .ToList();
 
-         if (_forbiddenNamesRetriever.For(simulation).Contains(simulationName))
-            throw new InvalidOperationException("Simulation name is forbidden");
+         var errors = messages
+            .Where(m => m.NotificationType == NotificationType.Error)
+            .Select(m => m.Text)
+            .ToList();
```
Comment (rwmcintosh) [inline src/MoBi.R/Services/SimulationFactory.cs]: in here messages should be evaluated to a list before it's used.

File: tests/MoBi.R.Tests/AllCalculationMethods.pkml
Comment (rwmcintosh) [inline tests/MoBi.R.Tests/AllCalculationMethods.pkml:1]: This file should be removed from the folder and from revision control. It should be a linked instance from `src\Data`

File: tests/MoBi.R.Tests/MoBi.R.Tests.csproj [hunk 12]
```diff
@@ -41,6 +41,9 @@
   </ItemGroup>
 
   <ItemGroup>
+    <None Update="AllCalculationMethods.pkml">
+      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
+    </None>
```
Comment (rwmcintosh) [inline tests/MoBi.R.Tests/MoBi.R.Tests.csproj]: Should be a linked instance

**Review by rwmcintosh — CHANGES_REQUESTED** [review]

**Comment by rwmcintosh** [comment]
Make sure to also check that all the `usings` are removed if not needed. ReSharper does it for you.

File: src/MoBi.Core/Exceptions/MoBiException.cs (hunk 8 above)
[the remark this answers is not in the document]
Comment (rwmcintosh) [reply src/MoBi.Core/Exceptions/MoBiException.cs]: The only reason I would insist on it is because if we leave it in random order then when we do use ReSharper in another PR then it creates noise.

We could disable it in ReSharper, but it's basically a free fix and all files should be cleaned by ReSharper before committing anyway.

[the remark this answers is not in the document]
Comment (Yuri05) [reply src/MoBi.Core/Exceptions/MoBiException.cs]: I am not telling we should disable it - I just was not aware of this "natural" order :)

[the remark this answers is not in the document]
Comment (Yuri05) [reply src/MoBi.Core/Exceptions/MoBiException.cs]: btw., the reaction of Copilot to my remark above (https://github.com/Open-Systems-Pharmacology/MoBi/pull/2238#discussion_r2721176960) was opening a new PR (which changed nothing - https://github.com/Open-Systems-Pharmacology/MoBi/pull/2242) - pretty weird.
@coderabbitai seems to be much better in such interactions :)

File: tests/MoBi.R.Tests/AllCalculationMethods.pkml
Comment (rwmcintosh) [reply tests/MoBi.R.Tests/AllCalculationMethods.pkml:1]: It's still in the PR and in the file system in the tests project

Comment (rwmcintosh) [inline tests/MoBi.R.Tests/AllCalculationMethods.pkml:1]: File still present. It has to be removed.

**Review by rwmcintosh — CHANGES_REQUESTED** [review]

**Review by rwmcintosh — APPROVED** [review]

File: src/MoBi.R/Bootstrap/ApplicationStartup.cs [hunk 13]
```diff
@@ -16,16 +18,36 @@ internal class ApplicationStartup
...
+
+      private static CoreCalculationMethod createDefaultCalculationMethodForCategory(string category, IObjectBaseFactory objectBaseFactory)
+      {
+         var cm = objectBaseFactory.Create<CoreCalculationMethod>()
+            .WithName(AppConstants.DefaultNames.EmptyCalculationMethod)
+            .WithDescription(AppConstants.DefaultNames.EmptyCalculationMethodDescription);
+
+         cm.Category = category;
+         return cm;
       }
```
Comment (Yuri05) [inline src/MoBi.R/Bootstrap/ApplicationStartup.cs]: AFAICS: the code of these 2 functions is copied from **MoBi.UI/Services/ApplicationStartup.cs**.
Consider moving to another service which is accessible both from MoBi.UI and MoBi.R.
https://github.com/Open-Systems-Pharmacology/MoBi/blob/97e1b2ef38745fa164b828753b83bbc7e2ca4243/src/MoBi.UI/Services/ApplicationStartup.cs#L170-L188

File: src/MoBi.R/Bootstrap/ApplicationStartup.cs [hunk 14]
```diff
@@ -16,16 +18,36 @@ internal class ApplicationStartup
       public static void Initialize(ApiConfig apiConfig)
       {
          OSPSuite.R.Api.InitializeOnce(apiConfig, registerAction);
-
          new SerializerRegister().PerformMappingForMoBiSerializerRepository(OSPSuite.R.Api.Container);
+         initCalculationMethodRepository(OSPSuite.R.Api.Container);
+      }
```
Comment (Yuri05) [inline src/MoBi.R/Bootstrap/ApplicationStartup.cs]: Comparing this with the initialization of **MoBi.UI**: are another initializations not required here? Or are they just executed elsewhere?

https://github.com/Open-Systems-Pharmacology/MoBi/blob/97e1b2ef38745fa164b828753b83bbc7e2ca4243/src/MoBi.UI/Services/ApplicationStartup.cs#L110-L124

Comment (benjaperez1983) [reply src/MoBi.R/Bootstrap/ApplicationStartup.cs]: Well	most MoBi.UI initialization is UI-specific, while MoBi.R relies on OSPSuite.R.Api.InitializeOnce for core/infrastructure, plus serializer mapping and shared Calculation Methods init, so nothing else is required by default.

Comment (Yuri05) [reply src/MoBi.R/Bootstrap/ApplicationStartup.cs]: ok, thx

**Review by Yuri05 — APPROVED** [review]
