### PR TITLE
#1631 PV BB adding parameter values does not work as expected

### LINKED ISSUE #1631: PV BB: Adding parameter values for "MoleculeProperties" does not work as expected
Open any PK-Sim module, and try to add a new parameter value.
In the tree view, select the parameter `Intestinal permeability (paracellular)` of any molecule (full path: Spatial Structure|\<MoleculeName>|Intestinal permeability (paracellular)`) and "add" it:

image

The added path contains the key word `MoleculeProperties` and not the molecule name. Expected path: `nAb|Intestinal permeability (paracellular)`. This happens to the parameters that are defined as `MoleculeProperties` in the spatial structure:

image

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #1631

# Description

Adding parameter values for "MoleculeProperties" does not work as expected

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [ ] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs [hunk 1]
```diff
@@ -56,6 +57,30 @@ public override IEnumerable<ObjectBaseDTO> GetChildObjects(ObjectBaseDTO dto)
...
+               item.ReplaceWith(item.PathAsString.Replace(Constants.MOLECULE_PROPERTIES, parentName).ToPathArray());
+            }
+         }
+      }
+
+      private string getParentNameFromSelection() =>
+         _view.AllSelectedDTOs
+            .OfType<DummyParameterDTO>()
+            .FirstOrDefault()?.ModelParentName ?? string.Empty;
+
```
Comment (Yuri05) [inline src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs:83]: it is possible to multiselect parameters from several nodes.
I think, in this case `.FirstOrDefault()` might return the wrong parent node (e.g. `Organism` in the example below) ??
{DD3E9E05-27DD-45F0-8985-79F2F28BFE4F}

Comment (Yuri05) [reply src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs:83]: get parent name **for each selection separately**, no?
Otherwise if you multiselect 2 parameters from 2 different compounds, we will have the same problem (and now the same DTO type).

File: src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs [hunk 2]
```diff
@@ -56,6 +57,44 @@ public override IEnumerable<ObjectBaseDTO> GetChildObjects(ObjectBaseDTO dto)
...
+      }
+
+      private IReadOnlyList<ObjectPath> replaceMoleculePropertiesWithMoleculeName(
+         IReadOnlyList<IEntity> selectedItems,
+         IReadOnlyList<DummyParameterDTO> selectedParameterDtos)
+      {
+         var newItems = new List<ObjectPath>();
+         foreach (var item in selectedItems)
+         {
+            var temAsPath = CreatePathFor(item);
```
Comment (Yuri05) [inline src/MoBi.Presentation/Presenter/SelectReferenceAtParameterValuePresenter.cs:78]: @benjaperez1983 Looks good.
Just a typo (I assume `temAsPath `was supposed to be `itemAsPath `:)

**Review by rwmcintosh — APPROVED** [review]
