### PR TITLE
Fixes #1045 Silent crash when creating a circular reference

### LINKED ISSUE #509: Crash when creating a circular reference
1) Open MoBi
2) Create new project
3) In the SpatialStructures-BB (or any other - doesn't matter) create a parameter with the name "Parameter" (name doesn't matter).
4) Change it's value to an explicit formula
5) Create a new reference with the path "..|Parameter" and alias name "Parameter".
6) Type in "Parameter" into the formula field - silent crash.

Sometimes it crashes directly after entering "..|Parameter" into the path field.

### LINKED ISSUE #1045: Silent crash when creating a circular reference
- Create an empty MoBi project
- In the spatial structures BB, create a parameter in the "Individuals"-BB. Name: "test", formula type - "explicit formula"
- Create a formula with one variable "test", path = `..|test`
image

Click OK -> MoBi disappears.

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1045
Fixes #509

# Description
When adding a new alias in an explicit formula it was possible to crash MoBi on a stack overflow exception.

This is just an explicit check to make sure that the new path does not create a circular reference. The exception throw is the same as the strategy when creating a new parameter.

This fixes both issues because we are catching the circular reference at the stage where the path is entered, which is common to creating or editing a parameter formula. You will not be able to enter the value like this as described in the issue.

image

The exception is thrown for a different parameter name, but the dialog is shown and then the value is cleared

image

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs [hunk 1]
```diff
@@ -124,6 +124,9 @@ public void SetFormulaUsablePath(string newPath, FormulaUsablePathDTO dto)
          var path = new ObjectPath(newPath.ToPathArray());
          var formulaUsablePath = _formula.FormulaUsablePathBy(dto.Alias);
 
+         if (_circularReferenceChecker.HasCircularReference(path, _formulaOwner))
```
Comment (msevestre) [inline src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs:127]: I think we removed it because it takes way too much time on big projects
That's why it also became an option in the user settings.. Adding it back will create other issus but might be wrong

Comment (rwmcintosh) [reply src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs:127]: Is that an option only when building a simulation or also when entering each alias?

Comment (rwmcintosh) [reply src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs:127]: So, should I surround this with an option check or what do you think?

Comment (msevestre) [reply src/MoBi.Presentation/Presenter/EditFormulaPathListPresenter.cs:127]: I really don't know. I remember a time where EDITING of a fomula took forever in a project (from @PavelBal ) in fact
So we removed this But maybe it was due to the formula ?

**Comment by PavelBal** [comment]
Well I don't know what this change does. I can't remember any more what the exact performance issue was, but it was a pain.

I imagine now it fails once it tries to evaluate the formula? Can't you just catch it and WHEN THE EXCEPTION IS THROWN, perform the circular check and inform the user about a potential problem?

**Comment by rwmcintosh** [comment]
No, a stack overflow exception is terminal. You can only catch it when running it in a debugger. AFAIK.

**Review by Yuri05 — APPROVED** [review]
