### PR TITLE
Fixes #987 Import Expression as PSV is on the wrong node

### LINKED ISSUE #987: Import Expression as PSV is on the wrong node
That last context menu should be at the PSV folder level

image

### PR DESCRIPTION
**Pull request by rwmcintosh**

### CODE REVIEW

File: src/MoBi.Presentation/DTO/ObjectBaseDTO.cs [hunk 1]
```diff
@@ -158,4 +159,14 @@ public ModuleViewItem(Module module)
          Module = module;
       }
    }
+
+   public class ModuleParameterStartValuesCollectionViewItem : ObjectBaseDTO
```
Comment (msevestre) [inline src/MoBi.Presentation/DTO/ObjectBaseDTO.cs:163]: I don't understand this object. It's the same as the ModuleViewItem above? 🤔

**Review by msevestre — CHANGES_REQUESTED** [review]
I do not think that we need two objects that are virtually identical just of the sake of context menu. Something is a bit off. The IsSatisfy can use another condition maybe?

File: src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterStartValuesFolder.cs [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+         var contextMenu = new ContextMenuForParameterStartValuesFolder(_container);
+         return contextMenu.InitializeWith(viewItem.DowncastTo<ModuleViewItem>(), presenter);
+      }
+
+      public bool IsSatisfiedBy(IViewItem viewItem, IPresenterWithContextMenu<IViewItem> presenter)
+      {
+         if (!(viewItem is ModuleViewItem moduleViewItem))
+            return false;
+
+         return moduleViewItem.TargetAsObject.IsAnImplementationOf<IEnumerable<ParameterStartValuesBuildingBlock>>();
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/MenusAndBars/ContextMenus/ContextMenuForParameterStartValuesFolder.cs:69]: Like this?
