### PR TITLE
Fixes #2116 Adding a physical container to a spatial structure does not register the MoleculeProperties container

### LINKED ISSUE #2116: Adding a physical container to a spatial structure does not register the MoleculeProperties container
[TGI_01.zip](https://github.com/user-attachments/files/22496032/TGI_01.zip)

Image

In the attached project, in the marked module, click "New Parameter Value" in the PV BB

Try to expand "Tumor growth  - Intracellular"

Image

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MoBi.Presentation.Presenter.SelectReferencePresenterBase.AddChildrenFromDummyMolecule(List`1 children, DummyMoleculeContainerDTO dummyMolecule)
   at MoBi.Presentation.Presenter.SelectReferencePresenterBase.GetChildObjects(ObjectBaseDTO dto)
   at MoBi.Presentation.Presenter.SelectReferenceAtParameterValuePresenter.GetChildObjects(ObjectBaseDTO dto)
   at MoBi.Presentation.Mappers.ObjectBaseDTOToReferenceNodeMapper.<MapFrom>b__4_0(ObjectBaseDTO x)
   at MoBi.Presentation.Nodes.HierarchicalStructureNode.get_Children()
   at OSPSuite.UI.Controls.UxTreeView.beforeNodeExpand(Object sender, BeforeExpandEventArgs e)
   at DevExpress.XtraTreeList.TreeList.RaiseBeforeExpand(TreeListNode node)
   at DevExpress.XtraTreeList.TreeList.OnExpanded(TreeListNode node)
   at DevExpress.XtraTreeList.Nodes.TreeListNode.OnExpandedChanged(Boolean value)
   at DevExpress.XtraTreeList.TreeList.ExpandNodeAnimation(TreeListNode node, Boolean value)
   at DevExpress.XtraTreeList.Handler.TreeListHandler.NormalState.MouseDown(MouseEventArgs e, TreeListHitTest ht)
   at DevExpress.XtraTreeList.Handler.TreeListHandler.OnMouseDown(MouseEventArgs e)
   at DevExpress.XtraTreeList.TreeList.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraTreeList.TreeList.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9310.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MoBi
    Assembly Version: 12.1.227.0
    Win32 Version: 12.1.227.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/MoBi.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9310.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Utils.v21.2.DLL
----------------------------------------
DevExpress.Data.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Data.v21.2.DLL
----------------------------------------
OSPSuite.Utility
    Assembly Version: 4.1.1.1
    Win32 Version: 4.1.1.1
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Utility.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
MoBi.UI
    Assembly Version: 12.1.227.0
    Win32 Version: 12.1.227.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/MoBi.UI.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9316.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
OSPSuite.Core
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Core.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DevExpress.Data.Desktop.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Data.Desktop.v21.2.DLL
----------------------------------------
OSPSuite.Infrastructure.Castle
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Infrastructure.Castle.DLL
----------------------------------------
Castle.Windsor
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Castle.Windsor.DLL
----------------------------------------
OSPSuite.Presentation
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Presentation.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 9.0.0.2
    Win32 Version: 9.0.225.6610
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
MoBi.Core
    Assembly Version: 12.1.227.0
    Win32 Version: 12.1.227.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/MoBi.Core.DLL
----------------------------------------
MoBi.Presentation
    Assembly Version: 12.1.227.0
    Win32 Version: 12.1.227.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/MoBi.Presentation.DLL
----------------------------------------
OSPSuite.UI
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.UI.DLL
----------------------------------------
OSPSuite.Assets.Images
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Assets.Images.DLL
----------------------------------------
OSPSuite.Assets
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Assets.DLL
----------------------------------------
Northwoods.Go
    Assembly Version: 6.3.1.47
    Win32 Version: 6.3.1.47
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Northwoods.Go.DLL
----------------------------------------
Castle.Core
    Assembly Version: 5.0.0.0
    Win32 Version: 5.1.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Castle.Core.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9310.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/System.ValueTuple.DLL
----------------------------------------
OSPSuite.Infrastructure.Import
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Infrastructure.Import.DLL
----------------------------------------
System.Drawing.Common
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.225.6608
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/System.Drawing.Common.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
DevExpress.RichEdit.v21.2.Core
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.RichEdit.v21.2.Core.DLL
----------------------------------------
DevExpress.Office.v21.2.Core
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Office.v21.2.Core.DLL
----------------------------------------
DevExpress.XtraBars.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraBars.v21.2.DLL
----------------------------------------
DevExpress.XtraEditors.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraEditors.v21.2.DLL
----------------------------------------
DevExpress.XtraRichEdit.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraRichEdit.v21.2.DLL
----------------------------------------
DevExpress.XtraGrid.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraGrid.v21.2.DLL
----------------------------------------
DevExpress.XtraTreeList.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraTreeList.v21.2.DLL
----------------------------------------
Northwoods.Go.Layout
    Assembly Version: 6.3.1.47
    Win32 Version: 6.3.1.47
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Northwoods.Go.Layout.DLL
----------------------------------------
DevExpress.XtraPivotGrid.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraPivotGrid.v21.2.DLL
----------------------------------------
DevExpress.PivotGrid.v21.2.Core
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.PivotGrid.v21.2.Core.DLL
----------------------------------------
DevExpress.XtraCharts.v21.2.UI
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraCharts.v21.2.UI.DLL
----------------------------------------
DevExpress.XtraCharts.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraCharts.v21.2.DLL
----------------------------------------
DevExpress.Charts.v21.2.Core
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Charts.v21.2.Core.DLL
----------------------------------------
DevExpress.Printing.v21.2.Core
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Printing.v21.2.Core.DLL
----------------------------------------
DevExpress.XtraLayout.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraLayout.v21.2.DLL
----------------------------------------
OSPSuite.DataBinding
    Assembly Version: 3.0.1.1
    Win32 Version: 3.0.1.1
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.DataBinding.DLL
----------------------------------------
MoBi.Engine
    Assembly Version: 12.1.227.0
    Win32 Version: 12.1.227.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/MoBi.Engine.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MoBi.Assets
    Assembly Version: 12.1.227.0
    Win32 Version: 12.1.227.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/MoBi.Assets.DLL
----------------------------------------
System.Resources.Extensions
    Assembly Version: 9.0.0.5
    Win32 Version: 9.0.525.21509
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/System.Resources.Extensions.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/System.Numerics.Vectors.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 5.1.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Castle.Core.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
OSPSuite.Serializer
    Assembly Version: 4.0.1.3
    Win32 Version: 4.0.1.3
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Serializer.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OSPSuite.SimModel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.SimModel.DLL
----------------------------------------
OSPSuite.FuncParser
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.FuncParser.DLL
----------------------------------------
OSPSuite.Infrastructure.Serialization
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Infrastructure.Serialization.DLL
----------------------------------------
OSPSuite.Infrastructure.Reporting
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Infrastructure.Reporting.DLL
----------------------------------------
NHibernate
    Assembly Version: 5.5.0.0
    Win32 Version: 5.5.2.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/NHibernate.DLL
----------------------------------------
FluentNHibernate
    Assembly Version: 3.4.0.0
    Win32 Version: 3.4.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/FluentNHibernate.DLL
----------------------------------------
OSPSuite.TeXReporting
    Assembly Version: 3.0.1.1
    Win32 Version: 3.0.1.1
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.TeXReporting.DLL
----------------------------------------
OSPSuite.Infrastructure.Export
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Infrastructure.Export.DLL
----------------------------------------
OSPSuite.Infrastructure
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Infrastructure.DLL
----------------------------------------
OSPSuite.Presentation.Serialization
    Assembly Version: 12.1.128.0
    Win32 Version: 12.1.128.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.Presentation.Serialization.DLL
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
OSPSuite.DataBinding.DevExpress
    Assembly Version: 6.0.1.2
    Win32 Version: 6.0.1.2
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/OSPSuite.DataBinding.DevExpress.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9316.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
DevExpress.Pdf.v21.2.Core
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Pdf.v21.2.Core.DLL
----------------------------------------
DevExpress.Images.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.Images.v21.2.DLL
----------------------------------------
DevExpress.XtraPrinting.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraPrinting.v21.2.DLL
----------------------------------------
DevExpress.BonusSkins.v21.2
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.BonusSkins.v21.2.DLL
----------------------------------------
Northwoods.Go.Xml
    Assembly Version: 6.3.1.47
    Win32 Version: 6.3.1.47
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Northwoods.Go.Xml.DLL
----------------------------------------
DevExpress.XtraCharts.v21.2.Wizard
    Assembly Version: 21.2.15.0
    Win32 Version: 21.2.15.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/DevExpress.XtraCharts.v21.2.Wizard.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9316.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Antlr3.Runtime
    Assembly Version: 3.5.0.2
    Win32 Version: 3.5.1.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Antlr3.Runtime.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 1.4.2.13
    Win32 Version: 1.4.2.13
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/ICSharpCode.SharpZipLib.DLL
----------------------------------------
NPOI.Core
    Assembly Version: 2.7.2.0
    Win32 Version: 2.7.2.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/NPOI.Core.DLL
----------------------------------------
NPOI.OOXML
    Assembly Version: 2.7.2.0
    Win32 Version: 2.7.2.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/NPOI.OOXML.DLL
----------------------------------------
NPOI.OpenXml4Net
    Assembly Version: 2.7.2.0
    Win32 Version: 2.7.2.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/NPOI.OpenXml4Net.DLL
----------------------------------------
NPOI.OpenXmlFormats
    Assembly Version: 2.7.2.0
    Win32 Version: 2.7.2.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/NPOI.OpenXmlFormats.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.119.0
    Win32 Version: 1.0.119.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Iesi.Collections
    Assembly Version: 4.0.0.4000
    Win32 Version: 4.0.4.0
    CodeBase: file:///C:/Program%20Files/Open%20Systems%20Pharmacology/MoBi%2012.1/Iesi.Collections.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2116 

# Description
The sub containers were not registered when a new container is added to a spatial structure with "MoleculeProperties" already added.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/EditContainerPresenter.cs [hunk 1]
```diff
@@ -208,15 +208,16 @@ public override IBuildingBlock BuildingBlock
       public override void Edit(IContainer container, IReadOnlyList<IObjectBase> existingObjectsInParent)
       {
          _container = container;
-         //an unnamed container means it is being created now, since the name is mandatory over the creation.
-         _isNewEntity = string.IsNullOrEmpty(_container.Name);
+         // containers that have already been registered are not considered new and must use commands
+         // for adding and removing subcontainers
+         _isNewEntity = _context.Get(container.Id) == null;
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/EditContainerPresenter.cs:213]: The official fix is here. It's not enough to check if the name is empty. We are going to consider this not new for the purposes of editing if the container is already added to the project.

The editor is used in two ways, one for in-place editing containers, and also for editing in a modal when a container is added to the structure.

The hitch in the second case is that the container is already added to the project before the modal is displayed. I think this is because the nested editors expect to be able to edit formulas and other entities by retrieving them from the project.

In any case if we can find the container already in the project then we should edit using commands.

File: src/MoBi.Core/Commands/AddObjectBaseCommand.cs [hunk 2]
```diff
@@ -10,40 +11,42 @@ public abstract class AddObjectBaseCommand<TChild, TParent> : AddItemCommand<TCh
...
          Description = AppConstants.Commands.AddToDescription(ObjectType, _itemToAdd.Name, _parent.Name, context.TypeFor(_buildingBlock), _buildingBlock.Name);
-         context.Register(_itemToAdd);
+         register(_itemToAdd, context);
          AddTo(_itemToAdd, _parent, context);
 
          if (!Silent)
             context.PublishEvent(new AddedEvent<TChild>(_itemToAdd, _parent));
       }
 
+      private void register(TChild itemToAdd, IMoBiContext context) => context.Resolve<IRegisterTask>().RegisterAllIn(itemToAdd);
```
Comment (rwmcintosh) [inline src/MoBi.Core/Commands/AddObjectBaseCommand.cs:42]: Even though this is not really required for this bug, we should always register everything in a container when it's added.

File: src/MoBi.Core/Commands/RemoveObjectBaseCommand.cs [hunk 3]
```diff
@@ -20,16 +21,18 @@ protected override void ExecuteWith(IMoBiContext context)
          base.ExecuteWith(context);
          Description = AppConstants.Commands.RemoveFromDescription(ObjectType, _itemToRemove.Name, _parent.Name, context.TypeFor(_buildingBlock), _buildingBlock.Name);
          RemoveFrom(_itemToRemove, _parent, context);
-         context.Unregister(_itemToRemove);
+         unRegister(_itemToRemove, context);
          context.PublishEvent(new RemovedEvent(_itemToRemove, _parent));
       }
 
+      private void unRegister(TChild itemToRemove, IMoBiContext context) => context.Resolve<IUnregisterTask>().UnregisterAllIn(itemToRemove);
```
Comment (rwmcintosh) [inline src/MoBi.Core/Commands/RemoveObjectBaseCommand.cs:28]: and unregister everything that's being removed from a project.

**Review by Yuri05 — APPROVED** [review]
