### PR TITLE
Fixes #1618 It should not be possible to create multiple neighborhoods with same neighbors

### LINKED ISSUE #1618: It should not be possible to create multiple neighborhoods with same neighbors
[neighborhoods-diff-name-same-neighbors.zip](https://github.com/user-attachments/files/17630328/neighborhoods-diff-name-same-neighbors.zip)

Currently, it is possible to create multiple neighborhoods between the same two containers but with different names. This can result in transport processes being created multiple times and unexpected model behavior (spent almost 5 hours debugging a project).

This should not be allowed; only one neighborhood between the same two containers should be allowed. Therefore, at the simulation creation step (when combining the modules), for each NEW neighborhood (i.e., the neighborhood with a new name), it should be checked whether a neighborhood between the specified containers already exists (disregarding what the first or the second neighbor is). 

To speed up the process, maintain a map of neighborhood paths that are already connected?

If a new neighborhood between two already connected containers is being added, show an error "Neighborhood \<NeighborhoodName> cannot be created because a neighborhood between the containers \<Container1> and \<Container2> already exists. Every pair of containers can be connected by one neighborhood only".

Attached is a project for testing. It contains three modules and three combinations of the modules (simulations). "Module 1" has three containers - A, B, and C, and the neighborhoods between containers A and B and between B and C, and the simulation "Valid_Simulation" can be created from this one module:

image

Module 2 defines a neighborhood between containers B and A, and it is combined with the first module to the simulation "Invalid_1", which has two neighborhoods between A and B. This should NOT be allowed:

image

Module 3 defines a neighborhood between A and B (the same as Module 1, but with a different name). It is combined with the first module to the simulation "Invalid_2", which again has two neighborhoods between A and B. This should NOT be allowed:

image

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1618

# Description
Making sure that when a user creates a new neighborhood within a spatial structure, that one does not already exist for those two neighbors.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
Creating new neighborhoods:
image

image

Editing neighbors in an existing neighborhood
image

image

When you hand edit the paths
image

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/DTO/NeighborhoodBuilderDTO.cs [hunk 1]
```diff
@@ -1,15 +1,56 @@
...
+      {
+         var uniqueNeighbors = existingNeighborhoods.SelectMany(x => new[] { x.FirstNeighborPath, x.SecondNeighborPath }).Distinct().Where(x => x != null);
+         _connections = new Cache<string, List<string>>();
+
+         uniqueNeighbors.Each(x =>
+         {
+            existingNeighborhoods.Where(y => Equals(y.FirstNeighborPath, x)).Each(y => addConnection(_connections, x, y.SecondNeighborPath));
+            existingNeighborhoods.Where(y => Equals(y.SecondNeighborPath, x)).Each(y => addConnection(_connections, x, y.FirstNeighborPath));
+         });
+      }
```
Comment (Yuri05) [inline src/MoBi.Presentation/DTO/NeighborhoodBuilderDTO.cs:42]: don't understand the workflow. Why not just 
`existingNeighborhoods.Each(nbh => addConnection(_connections, nbh.FirstNeighborPath, nbh.SecondNeighborPath)`

And `addConnection()` should check that both paths are not null before adding the connection

**Review by Yuri05 — APPROVED** [review]
