### PR TITLE
Fixes #1498

### LINKED ISSUE #1498: When neighborhood is not present and selected diagram throws exception
See this comment - https://github.com/Open-Systems-Pharmacology/MoBi/pull/1469#issuecomment-2296990955

To reproduce, select the diagram tab

image

When the diagram has not been viewed, the Selection event is unhandled. We will need to check if the handled object is null

```
     public void Handle(EntitySelectedEvent eventToHandle)
     {
        if (DiagramManager == null)
           return;
...
```

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1498
The selection of a neighborhood that wasn't present in the spatial structure triggered other presenters to also respond. That's changed so that only the responsible presenter will respond.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/EditBuildingBlockPresenterBase.cs [hunk 1]
```diff
@@ -85,16 +85,16 @@ private void selectObjectAndContainer(IContainer containerObject, IObjectBase se
 
       public void Handle(EntitySelectedEvent eventToHandle)
       {
-         var selectedObject = eventToHandle.ObjectBase;
-         var (canHandle, containerObject) = CanHandle(selectedObject);
-         if (!canHandle && selectedObject != null)
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/EditBuildingBlockPresenterBase.cs:90]: This was the issue. This base presenter was handling all `null` selections. That meant that all open presenters would "handle" this by making themselves visible.

We don't want this, instead we want to isolate the null selection to the EditSpatialStructurePresenter where the selection event was raised

File: src/MoBi.Presentation/Presenter/EditSpatialStructurePresenter.cs [hunk 2]
```diff
@@ -78,18 +78,21 @@ private void setInitialView()
 
       public override object Subject => _spatialStructure;
 
-      protected override (bool canHandle, IContainer containerObject) SpecificCanHandle(IObjectBase selectedObject)
+      protected override (bool canHandle, IContainer containerObject) SpecificCanHandle(EntitySelectedEvent entitySelectedEvent)
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/EditSpatialStructurePresenter.cs:81]: This is the reason for all the various changes. The signature of this virtual method had to change so I could determine if the sender of the event was the subpresenter, and if so, handle the event.

**Review by benjaperez1983 — APPROVED** [review]

**Review by Yuri05 — APPROVED** [review]
