### PR TITLE
#1437  fix possible null reference

### LINKED ISSUE #1437: Exception when creating an new IC BB
[TwoContainer_V2.zip](https://github.com/user-attachments/files/16377144/TwoContainer_V2.zip)

In the attached project, open the module "Pysical containers - Molecule A", right click on "Initial Conditions" and select "Create..."

image

Exception:

Application:
MoBi® 12.0.291

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Presenter.AddContentToModulePresenter`2.AddMoleculesSelectionChanged(Boolean moleculesSelected)
   at MoBi.UI.Views.AddContentToModuleView`2.moleculesChanged()
   at OSPSuite.UI.Views.BaseView.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #1437 

# Description

Fix a null referenced object when creating a new Initial Condition

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/AddContentToModulePresenter.cs [hunk 1]
```diff
@@ -23,7 +23,7 @@ protected AddContentToModulePresenter(TView view) : base(view)
 
       public void AddMoleculesSelectionChanged(bool moleculesSelected)
       {
-         if (!moleculesSelected || Module.InitialConditionsCollection.Any())
+         if (!moleculesSelected || (Module?.InitialConditionsCollection != null && Module.InitialConditionsCollection.Any()))
```
Comment (rwmcintosh) [inline src/MoBi.Presentation/Presenter/AddContentToModulePresenter.cs:26]: I think there is an earlier issue than this. By the time this get's called, the presenter should already be initialized and that initialization should always include the module to which we are adding initial conditions.

Can you check what happens when you left click, then select "Add Building Block" the pick "Initial Conditions" I think the Module will be non-null.

**Review by rwmcintosh — CHANGES_REQUESTED** [review]

File: src/MoBi.Presentation/Presenter/AddContentToModulePresenter.cs (hunk 1 above)
Comment (benjaperez1983) [reply src/MoBi.Presentation/Presenter/AddContentToModulePresenter.cs]: Yeah, I`ve made some analysis before submitting.
As you mention, the only place where we initialize this variable is on the "AddBuildingBlocksToModule" method:
image

Other than that, the Module property is null.
What I think (might be mistaken of course), is that this module variable is being set only on this public method, instead of the private method (with the same name) for a reason, but checking references, I can see that this property is only being used for this case mentioned on the ticket, so it might be safe to move it into the private method.

Let me know your thoughts on this.

**Review by rwmcintosh — APPROVED** [review]

**Review by Yuri05 — APPROVED** [review]
