### PR TITLE
Fixes #1842 Process rate parameter cannot be resolved when creating a simulation

### LINKED ISSUE #1842: Process rate parameter cannot be resolved when creating a simulation
It looks like the paths within the ProcessRate parameter are not properly resolved

> I have a simulation for which I want to plot a process rate. I opened the "Passive transport" BB and ticked the boxes "create process rate parameter" and "plot process rate parameter". The simulation used to run, but once these boxes ticked, I get the following error:

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #1842

# Description
Creating a reference in a transport builder should be more like creating a reference in a reaction builder.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/MoBi.Presentation/Presenter/ObjectPathCreatorAtProcessBuilder.cs [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+      {
+         var parentProcess = GetProcessBuilderFor(parameter);
+
+         // Always Absolute paths
+         if (parameter.BuildMode != ParameterBuildMode.Local)
+            return CreateFormulaUsablePathFrom(new[] { parentProcess.Name, parameter.Name }, parameter);
+
+         // Parameter is child of process
+         if (parentProcess.Equals(ProcessBuilder))
+            return CreateFormulaUsablePathFrom(new[] { parameter.Name }, parameter);
```
Comment (Yuri05) [inline src/MoBi.Presentation/Presenter/ObjectPathCreatorAtProcessBuilder.cs:25]: Is this correct? Shouldn't the path be `..|parameter.Name` and not just `parameter.Name`?

Comment (rwmcintosh) [reply src/MoBi.Presentation/Presenter/ObjectPathCreatorAtProcessBuilder.cs:25]: For ProcessRateParameter the ..| will be added when the parameter is created.

This just makes the alias path a relative path instead of absolute (from the builder root).

If the path is not relative, then when ProcessRate is created the ..| will not be added.

In core the service is called `ProcessRateParameterCreator`

Comment (Yuri05) [reply src/MoBi.Presentation/Presenter/ObjectPathCreatorAtProcessBuilder.cs:25]: and the function is called only for `ProcessRate `parameters? Or also for another transport/reaction parameters?

Comment (rwmcintosh) [reply src/MoBi.Presentation/Presenter/ObjectPathCreatorAtProcessBuilder.cs:25]: `ProcessRateParameterCreator` is used for `ProcessRate` parameters. Is that what you mean?

Comment (Yuri05) [reply src/MoBi.Presentation/Presenter/ObjectPathCreatorAtProcessBuilder.cs:25]: I meant, is the function here `protected FormulaUsablePath CreatePathToProcessProperty(IParameter parameter)` used only for `ProcessRate` parameters?

File: src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs [hunk 2]
```diff
@@ -123,13 +128,21 @@ private string getPathKeywordForContainer(IContainer container)
...
 
          return string.Empty;
       }
+
+      protected override TransportBuilder GetProcessBuilderFor(IParameter parameter)
+      {
+         if (parameter.IsAtTransport())
+            return parameter.RootContainer as TransportBuilder;
+
+         throw new MoBiException($"cant find transport for parameter {parameter.Name}");
```
Comment (msevestre) [inline src/MoBi.Presentation/Presenter/ObjectPathCreatorAtTransport.cs:145]: @rwmcintosh WOndering why we start to put error message directly into the code like this. I have seen in multiple times. Is this our new way of doing exception instead of collating the text in one central place?

**Review by msevestre — COMMENTED** [review]
Looks good to me. Just a phylosophical question really as to how we deal with error constant (I don't mean the debug stuff that can stay as is because it will never be shown to the user)
